version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "90:90"
    depends_on:
      - libros-service
      - usuarios-service
      - prestamos-service
    networks:
      - biblioteca-net

  usuarios-service:
    build: ./usuarios-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    networks:
      - biblioteca-net

  libros-service:
    build: ./libros-service
    ports:
      - "8081:8081"
    depends_on:
      - usuarios-service
    environment:
      - SERVER_PORT=8081
    networks:
      - biblioteca-net

  prestamos-service:
    build: ./prestamos-service
    ports:
      - "8083:8083"
    depends_on:
      - libros-service
      - usuarios-service
    environment:
      - SERVER_PORT=8083
    networks:
      - biblioteca-net

networks:
  biblioteca-net:
    driver: bridge